readme.txt, wpmktgengine-woocommerce.php
1)Updated version number as 1.7.3
=> updated the version number

readme.txt, wpmktgengine-woocommerce.php
1. Fixed simple products, variable products purchase.
2. Fixed logout user product purchase.
=> multi product orders

wpmktgengine-woocommerce.php
1)Fixed the issue with placing orders when user purchasing the product with coupon code.
=> passed finanical status in checkout-order-item hook

readme.txt, wpmktgengine-woocommerce.php
=> fixed function conflict

readme.txt, wpmktgengine-woocommerce.php
1)Fixed passing financial status as "paid".
=> passing financial status as paid

readme.txt, wpmktgengine-woocommerce.php
1)Passed financial status as paid.
=> financial status

readme.txt, wpmktgengine-woocommerce.php
1)Fixed new order notification while auto, manual renewals.
2)Fixed order total payment pass.
=> order total

readme.txt, wpmktgengine-woocommerce.php
1)Added function_exists to avoid the function conflicts.
=> added function exists

readme.txt, wpmktgengine-woocommerce.php
1)Removed function_exists from the plugin.
=> removed function_exists

includes/activitystream.js, includes/activitystreamtypes.css, wpmktgengine-woocommerce.php
1)Upgrader process complete for activity stream types.
=> upgrder process

readme.txt, wpmktgengine-woocommerce.php
=> version updates

readme.txt, wpmktgengine-woocommerce.php
1)Updated version number as 1.7.40.
=> updated version number as 1.7.40

includes/activitystream.js, includes/orderqueuescript.js, readme.txt, wpmktgengine-woocommerce.php
1)Fixed jquery conflict issue.
=> fixed jquery conflict

readme.txt, wpmktgengine-woocommerce.php
1)Fixed jquery conflict issue.
=> fixed jquery issue

readme.txt, wpmktgengine-woocommerce.php
1)Fixed the issue of subscription renewal order duplicating while inserting into the order queue table.
=> fixed subscription renewal order duplications

readme.txt, wpmktgengine-woocommerce.php
1)Order status processing update.
2)On hold subscription changes.
=> subscription on-hold changes

readme.txt, wpmktgengine-woocommerce.php
1)Stored default cron setup values into the database table.
=> default cron setup

readme.txt, wpmktgengine-woocommerce.php
1)Fixed the jquery conflict issue while Failed orders data table display.
=> fixed failed orders datatable jquery issue

includes/queuecronjob.php, readme.txt, wpmktgengine-woocommerce.php
1)Changed order status on the failed order queue.
=> changed orderstatus

wpmktgengine-woocommerce.php
- use subscription id for subscription order instead of order id
- send new order event for subscription order
=> Subscription issue
